/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.electionvotermanagement.presentation;

/**
 *
 * @author mfcaicedo
 */
public class GUIConsulta extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIConsulta
     */
    public GUIConsulta() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCentral = new javax.swing.JPanel();
        jLabelConsultaLugarVotacion = new javax.swing.JLabel();
        jLabelIdentifier = new javax.swing.JLabel();
        jtxtIdentifier = new javax.swing.JTextField();
        jLabelConsulta = new javax.swing.JLabel();
        jComboBoxEleccion = new javax.swing.JComboBox<>();
        jLabelVerificacion = new javax.swing.JLabel();
        jCheckBoxVerificacion = new javax.swing.JCheckBox();
        jButtonConsultar = new javax.swing.JButton();
        jLabelTituloResultado = new javax.swing.JLabel();
        jPanelResultado = new javax.swing.JPanel();
        jScrollPaneContTable = new javax.swing.JScrollPane();
        jTableResultado = new javax.swing.JTable();

        jLabelConsultaLugarVotacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelConsultaLugarVotacion.setText("CONSULTA LUGAR DE VOTACIÓN");

        jLabelIdentifier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdentifier.setText("NO. IDENTIFICACIÓN:");

        jLabelConsulta.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelConsulta.setText("SELECCIONE LA ELECCIÓN:");

        jComboBoxEleccion.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "LUGAR DE VOTACIÓN ACTUAL" }));

        jLabelVerificacion.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVerificacion.setText("MARQUE EL CUADRO DE VERIFICACIÓN:");

        jCheckBoxVerificacion.setText("No soy un robot");

        jButtonConsultar.setBackground(new java.awt.Color(0, 176, 172));
        jButtonConsultar.setText("CONSULTAR");

        jLabelTituloResultado.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloResultado.setText("INFORMACIÓN DEL LUGAR DE VOTACIÓN");

        jPanelResultado.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jTableResultado.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "IDENTIFICACIÓN", "NOMBRE", "LUGAR VOTACIÓN", "MESA"
            }
        ));
        jScrollPaneContTable.setViewportView(jTableResultado);

        javax.swing.GroupLayout jPanelResultadoLayout = new javax.swing.GroupLayout(jPanelResultado);
        jPanelResultado.setLayout(jPanelResultadoLayout);
        jPanelResultadoLayout.setHorizontalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelResultadoLayout.createSequentialGroup()
                .addContainerGap(14, Short.MAX_VALUE)
                .addComponent(jScrollPaneContTable, javax.swing.GroupLayout.PREFERRED_SIZE, 426, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
        );
        jPanelResultadoLayout.setVerticalGroup(
            jPanelResultadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelResultadoLayout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jScrollPaneContTable, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanelCentralLayout = new javax.swing.GroupLayout(jPanelCentral);
        jPanelCentral.setLayout(jPanelCentralLayout);
        jPanelCentralLayout.setHorizontalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addGap(35, 35, 35)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabelVerificacion)
                    .addComponent(jLabelConsulta)
                    .addComponent(jLabelIdentifier)
                    .addComponent(jLabelConsultaLugarVotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jtxtIdentifier)
                    .addComponent(jComboBoxEleccion, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jCheckBoxVerificacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButtonConsultar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(69, 69, 69)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanelCentralLayout.setVerticalGroup(
            jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCentralLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelConsultaLugarVotacion)
                    .addComponent(jLabelTituloResultado))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCentralLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanelCentralLayout.createSequentialGroup()
                        .addComponent(jLabelIdentifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jtxtIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelConsulta)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jComboBoxEleccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabelVerificacion)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jCheckBoxVerificacion)
                        .addGap(18, 18, 18)
                        .addComponent(jButtonConsultar))
                    .addComponent(jPanelResultado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(147, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jPanelCentral, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonConsultar;
    private javax.swing.JCheckBox jCheckBoxVerificacion;
    private javax.swing.JComboBox<String> jComboBoxEleccion;
    private javax.swing.JLabel jLabelConsulta;
    private javax.swing.JLabel jLabelConsultaLugarVotacion;
    private javax.swing.JLabel jLabelIdentifier;
    private javax.swing.JLabel jLabelTituloResultado;
    private javax.swing.JLabel jLabelVerificacion;
    private javax.swing.JPanel jPanelCentral;
    private javax.swing.JPanel jPanelResultado;
    private javax.swing.JScrollPane jScrollPaneContTable;
    private javax.swing.JTable jTableResultado;
    private javax.swing.JTextField jtxtIdentifier;
    // End of variables declaration//GEN-END:variables
}
