/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package co.unicauca.electionvotermanagement.presentation;

/**
 *
 * @author HP
 */
public class GUIMenu extends javax.swing.JFrame {

    /**
     * Creates new form GUIMenu
     */
    public GUIMenu() {
        initComponents();
        this.setLocationRelativeTo(null);
        invocarGUIConsulta();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jDesktopPaneEscritorio = new javax.swing.JDesktopPane();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenuConsultas = new javax.swing.JMenu();
        jMenuItemConLugVotacion = new javax.swing.JMenuItem();
        jMenuAdmin = new javax.swing.JMenu();
        jMenuItemAgregarLugaresVotacion = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        jMenuItemAgregarVotantes = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        jMenuItemAcercaDe = new javax.swing.JMenuItem();
        jMenuSalir = new javax.swing.JMenu();
        jMenuItemSalir = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jDesktopPaneEscritorioLayout = new javax.swing.GroupLayout(jDesktopPaneEscritorio);
        jDesktopPaneEscritorio.setLayout(jDesktopPaneEscritorioLayout);
        jDesktopPaneEscritorioLayout.setHorizontalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 923, Short.MAX_VALUE)
        );
        jDesktopPaneEscritorioLayout.setVerticalGroup(
            jDesktopPaneEscritorioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 463, Short.MAX_VALUE)
        );

        jMenuConsultas.setText("Consulta");

        jMenuItemConLugVotacion.setText("Consulta lugar votación ");
        jMenuItemConLugVotacion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemConLugVotacionActionPerformed(evt);
            }
        });
        jMenuConsultas.add(jMenuItemConLugVotacion);

        jMenuBar1.add(jMenuConsultas);

        jMenuAdmin.setText("Administración");

        jMenuItemAgregarLugaresVotacion.setText("Agregar lugares votación");
        jMenuAdmin.add(jMenuItemAgregarLugaresVotacion);
        jMenuAdmin.add(jSeparator1);

        jMenuItemAgregarVotantes.setText("Agregar votantes");
        jMenuAdmin.add(jMenuItemAgregarVotantes);

        jMenuBar1.add(jMenuAdmin);

        jMenu3.setText("Ayuda");

        jMenuItemAcercaDe.setText("Acerca de");
        jMenu3.add(jMenuItemAcercaDe);

        jMenuBar1.add(jMenu3);

        jMenuSalir.setText("Salir");

        jMenuItemSalir.setText("Salir");
        jMenuItemSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItemSalirActionPerformed(evt);
            }
        });
        jMenuSalir.add(jMenuItemSalir);

        jMenuBar1.add(jMenuSalir);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jDesktopPaneEscritorio)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jDesktopPaneEscritorio)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    /**
     * FUNCIONES PROGRAMADAS PARA DARLE FUNCIONALIDAD A LA APLICACIÓN 
     */
    /**
     * Método que invoca al jFrama interno de la consulta 
     */
    private void invocarGUIConsulta(){
        GUIConsulta objConsulta = new GUIConsulta();
        objConsulta.setMaximizable(true);
        this.jDesktopPaneEscritorio.add(objConsulta);
        objConsulta.show();
    }
    
    /**
     * Evento del jMenuItem salir 
     * @param evt 
     */
    private void jMenuItemSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemSalirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItemSalirActionPerformed
    /**
     * Acción del item de Consulta de lugar de votación 
     * @param evt 
     */
    private void jMenuItemConLugVotacionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItemConLugVotacionActionPerformed
        // TODO add your handling code here:
        invocarGUIConsulta();
    }//GEN-LAST:event_jMenuItemConLugVotacionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JDesktopPane jDesktopPaneEscritorio;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenuAdmin;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenu jMenuConsultas;
    private javax.swing.JMenuItem jMenuItemAcercaDe;
    private javax.swing.JMenuItem jMenuItemAgregarLugaresVotacion;
    private javax.swing.JMenuItem jMenuItemAgregarVotantes;
    private javax.swing.JMenuItem jMenuItemConLugVotacion;
    private javax.swing.JMenuItem jMenuItemSalir;
    private javax.swing.JMenu jMenuSalir;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    // End of variables declaration//GEN-END:variables
}
