package co.unicauca.electionvotermanagement.presentation;

import co.unicauca.electionvotermanagement.domain.Voter;
import co.unicauca.electionvotermanagement.domain.VotingPlace;
import co.unicauca.electionvotermanagement.service.Service;
import co.unicauca.electionvotermanagement.service.ServiceTable;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author mfcaicedo, danieleraso
 */
public class GUIVoters extends javax.swing.JInternalFrame {

    ArrayList<VotingPlace> lstVotingPlaces;
    int numTable;
    /**
     * Creates new form GUIVoters
     */
    public GUIVoters() throws SQLException {
        initComponents();
        lstVotingPlaces = new ArrayList<>();
        loadVotingPlace();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jLabelTituloVoters = new javax.swing.JLabel();
        jLabelFormRegistoVoters = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jtxtIdentifier = new javax.swing.JTextField();
        jLabelIdentifier = new javax.swing.JLabel();
        jtxtLastName = new javax.swing.JTextField();
        jLabelVotingPlace = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jLabelAddress1 = new javax.swing.JLabel();
        jComboBoxVotingPlaces = new javax.swing.JComboBox<>();
        jLabelVotingTable = new javax.swing.JLabel();
        jLabelAssignedTable = new javax.swing.JLabel();
        jButtonRegisterVoter = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(889, 460));

        jLabelTituloVoters.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloVoters.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloVoters.setText("GESTION DE VOTANTES");

        jLabelFormRegistoVoters.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelFormRegistoVoters.setText("FORMULARIO DE REGISTRO");

        jLabelLastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelLastName.setText("APELLIDOS:");

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelName.setText("NAME:");

        jLabelIdentifier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdentifier.setText("NO. IDENTIFICACIÓN (CC):");

        jLabelVotingPlace.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVotingPlace.setText("SELECCIONE EL LUGAR DE VOTACIÓN:");

        jLabelAddress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAddress1.setText("DIRECCIÓN:");

        jComboBoxVotingPlaces.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxVotingPlacesItemStateChanged(evt);
            }
        });

        jLabelVotingTable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVotingTable.setText("MESA DE VOTACIÓN:");

        jLabelAssignedTable.setText("Sin Asignar");

        jButtonRegisterVoter.setBackground(new java.awt.Color(0, 176, 172));
        jButtonRegisterVoter.setText("REGISTRAR");
        jButtonRegisterVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterVoterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloVoters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLastName)
                                    .addComponent(jtxtIdentifier)
                                    .addComponent(jLabelIdentifier)
                                    .addComponent(jtxtLastName)
                                    .addComponent(jLabelVotingPlace)
                                    .addComponent(jComboBoxVotingPlaces, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRegisterVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtName)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelAddress1)
                                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(jLabelVotingTable)
                                    .addComponent(jLabelAssignedTable))
                                .addGap(77, 77, 77))
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addComponent(jLabelFormRegistoVoters)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloVoters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFormRegistoVoters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addComponent(jLabelIdentifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtIdentifier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVotingPlace)
                            .addComponent(jLabelVotingTable)))
                    .addComponent(jLabelAddress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxVotingPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAssignedTable))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterVoter)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción del botón registrar votante 
     * @param evt 
     */
    private void jButtonRegisterVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterVoterActionPerformed
        // TODO add your handling code here:
        //recuperemos los valores 
        String lastNameVoter = this.jtxtLastName.getText();
        String nameVoter = this.jtxtName.getText();
        int identifierVoter = Integer.parseInt(this.jtxtIdentifier.getText());
        String addressVoter = this.jtxtDireccion.getText();
        String placeVoting = this.jComboBoxVotingPlaces.getSelectedItem().toString();
        String[] idPlaceVoting = placeVoting.split("_");
        int idPlace = Integer.parseInt(idPlaceVoting[1]);
        
        //1. crear el votante 
        Voter objVoter = new Voter(identifierVoter, nameVoter, lastNameVoter, addressVoter);
        ServiceTable objServiceTable = new ServiceTable();
        int respuesta = 0;
        try {
            respuesta = objServiceTable.addVoter(objVoter);
        } catch (SQLException ex) {
            Logger.getLogger(GUIVoters.class.getName()).log(Level.SEVERE, null, ex);
        }
        if (respuesta == 1) {
            
            try {
                //2. crear el votingTableVoter
                respuesta = objServiceTable.addVotingTableVoter(identifierVoter, numTable);
            } catch (SQLException ex) {
                Logger.getLogger(GUIVoters.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            JOptionPane.showInternalMessageDialog(this, "Votante insertado con éxito","Insertar votante", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showInternalMessageDialog(this, "Eror en la inserción del votante","Insertar votante", JOptionPane.ERROR_MESSAGE);
        }
        
        
        
        
        
        
    }//GEN-LAST:event_jButtonRegisterVoterActionPerformed
    /**
     * Detecta los cambios en el jComboBox
     * @param evt 
     */
    private void jComboBoxVotingPlacesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxVotingPlacesItemStateChanged
        // TODO add your handling code here:
        
        String placeVoting = this.jComboBoxVotingPlaces.getSelectedItem().toString();
        String[] idPlaceVoting = placeVoting.split("_");
        int idPlace = Integer.parseInt(idPlaceVoting[1]);
        //asigmación de la mesa al azar 
        assignedTableVoter(idPlace);
        
    }//GEN-LAST:event_jComboBoxVotingPlacesItemStateChanged
    /**
     * Métodos 
     */
    public void assignedTableVoter(int idPlace){
        VotingPlace objPlace = new VotingPlace();
        for (int i = 0; i < lstVotingPlaces.size(); i++) {
            if (lstVotingPlaces.get(i).getNitPlace() == idPlace) {
                objPlace = lstVotingPlaces.get(i);
            }
        }
        numTable = getRandomNumber(1, objPlace.getNumTables());
        String assignedTable = objPlace.getNamePlace() + "_" + numTable;
        this.jLabelAssignedTable.setText(assignedTable);
    }
    public int getRandomNumber(int min, int max) {
        return (int) ((Math.random() * (max - min)) + min);
    }
    public void loadVotingPlace() throws SQLException{
       Service objService = new Service();
      
       lstVotingPlaces = objService.loadVotingPlace();
        for (int i = 0; i < lstVotingPlaces.size(); i++) {
            this.jComboBoxVotingPlaces.addItem(lstVotingPlaces.get(i).getNamePlace() + "_"+lstVotingPlaces.get(i).getNitPlace());
        }
    }
    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegisterVoter;
    private javax.swing.JComboBox<String> jComboBoxVotingPlaces;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelAssignedTable;
    private javax.swing.JLabel jLabelFormRegistoVoters;
    private javax.swing.JLabel jLabelIdentifier;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTituloVoters;
    private javax.swing.JLabel jLabelVotingPlace;
    private javax.swing.JLabel jLabelVotingTable;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtIdentifier;
    private javax.swing.JTextField jtxtLastName;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
