package co.unicauca.electionvotermanagement.presentation;

/**
 *
 * @author mfcaicedo, danieleraso
 */
public class GUIVoters extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIVoters
     */
    public GUIVoters() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanelCenter = new javax.swing.JPanel();
        jLabelTituloVoters = new javax.swing.JLabel();
        jLabelFormRegistoVoters = new javax.swing.JLabel();
        jLabelLastName = new javax.swing.JLabel();
        jtxtName = new javax.swing.JTextField();
        jLabelName = new javax.swing.JLabel();
        jtxtLastName1 = new javax.swing.JTextField();
        jLabelIdentifier = new javax.swing.JLabel();
        jtxtLastName2 = new javax.swing.JTextField();
        jLabelVotingPlace = new javax.swing.JLabel();
        jtxtDireccion = new javax.swing.JTextField();
        jLabelAddress1 = new javax.swing.JLabel();
        jComboBoxVotingPlaces = new javax.swing.JComboBox<>();
        jLabelVotingTable = new javax.swing.JLabel();
        jLabelAssignedTable = new javax.swing.JLabel();
        jButtonRegisterVoter = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(889, 460));

        jLabelTituloVoters.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloVoters.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloVoters.setText("GESTION DE VOTANTES");

        jLabelFormRegistoVoters.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabelFormRegistoVoters.setText("FORMULARIO DE REGISTRO");

        jLabelLastName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelLastName.setText("APELLIDOS:");

        jLabelName.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelName.setText("NAME:");

        jLabelIdentifier.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelIdentifier.setText("NO. IDENTIFICACIÓN (CC):");

        jLabelVotingPlace.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVotingPlace.setText("SELECCIONE EL LUGAR DE VOTACIÓN:");

        jLabelAddress1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAddress1.setText("DIRECCIÓN:");

        jComboBoxVotingPlaces.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabelVotingTable.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVotingTable.setText("LUGAR DE VOTACIÓN:");

        jLabelAssignedTable.setText("Sin Asignar");

        jButtonRegisterVoter.setBackground(new java.awt.Color(0, 176, 172));
        jButtonRegisterVoter.setText("REGISTRAR");
        jButtonRegisterVoter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterVoterActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanelCenterLayout = new javax.swing.GroupLayout(jPanelCenter);
        jPanelCenter.setLayout(jPanelCenterLayout);
        jPanelCenterLayout.setHorizontalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloVoters, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addGap(37, 37, 37)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jLabelLastName)
                                    .addComponent(jtxtLastName1)
                                    .addComponent(jLabelIdentifier)
                                    .addComponent(jtxtLastName2)
                                    .addComponent(jLabelVotingPlace)
                                    .addComponent(jComboBoxVotingPlaces, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jButtonRegisterVoter, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jtxtName)
                                    .addComponent(jLabelName)
                                    .addComponent(jLabelAddress1)
                                    .addComponent(jtxtDireccion, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                                    .addComponent(jLabelVotingTable)
                                    .addComponent(jLabelAssignedTable))
                                .addGap(77, 77, 77))
                            .addGroup(jPanelCenterLayout.createSequentialGroup()
                                .addComponent(jLabelFormRegistoVoters)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))))
        );
        jPanelCenterLayout.setVerticalGroup(
            jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelCenterLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloVoters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabelFormRegistoVoters)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLastName)
                    .addComponent(jLabelName))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jtxtName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jtxtLastName2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelCenterLayout.createSequentialGroup()
                        .addComponent(jLabelIdentifier)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jtxtLastName1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jtxtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelVotingPlace)
                            .addComponent(jLabelVotingTable)))
                    .addComponent(jLabelAddress1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelCenterLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jComboBoxVotingPlaces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabelAssignedTable))
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterVoter)
                .addContainerGap(142, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanelCenter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción del botón registrar votante 
     * @param evt 
     */
    private void jButtonRegisterVoterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterVoterActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButtonRegisterVoterActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegisterVoter;
    private javax.swing.JComboBox<String> jComboBoxVotingPlaces;
    private javax.swing.JLabel jLabelAddress1;
    private javax.swing.JLabel jLabelAssignedTable;
    private javax.swing.JLabel jLabelFormRegistoVoters;
    private javax.swing.JLabel jLabelIdentifier;
    private javax.swing.JLabel jLabelLastName;
    private javax.swing.JLabel jLabelName;
    private javax.swing.JLabel jLabelTituloVoters;
    private javax.swing.JLabel jLabelVotingPlace;
    private javax.swing.JLabel jLabelVotingTable;
    private javax.swing.JPanel jPanelCenter;
    private javax.swing.JTextField jtxtDireccion;
    private javax.swing.JTextField jtxtLastName1;
    private javax.swing.JTextField jtxtLastName2;
    private javax.swing.JTextField jtxtName;
    // End of variables declaration//GEN-END:variables
}
