package co.unicauca.electionvotermanagement.presentation;

import co.unicauca.electionvotermanagement.domain.VotingPlace;
import co.unicauca.electionvotermanagement.service.ServiceVotingPlace;
import javax.swing.JOptionPane;

/**
 *
 * @author mfcaicedo, danieleraso
 */
public class GUIVotingPlace extends javax.swing.JInternalFrame {

    /**
     * Creates new form GUIVotingPlace
     */
    public GUIVotingPlace() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelTituloGestionLugarVotacion = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabelNamePlace = new javax.swing.JLabel();
        jtxtNamePlace = new javax.swing.JTextField();
        jLabelVotingCapacity = new javax.swing.JLabel();
        jtxtAddressPlace = new javax.swing.JTextField();
        jLabelAddressPlace1 = new javax.swing.JLabel();
        jSliderNumTables = new javax.swing.JSlider();
        jLabelNumTables1 = new javax.swing.JLabel();
        jSliderVoterCapacity = new javax.swing.JSlider();
        jButtonRegisterVotingPlace = new javax.swing.JButton();
        jLabelContNumTables = new javax.swing.JLabel();
        jLabelContVoterCapacity = new javax.swing.JLabel();

        setPreferredSize(new java.awt.Dimension(889, 460));

        jLabelTituloGestionLugarVotacion.setFont(new java.awt.Font("Dialog", 1, 18)); // NOI18N
        jLabelTituloGestionLugarVotacion.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabelTituloGestionLugarVotacion.setText("GESTIÓN LUGAR DE VOTACIÓN");

        jLabel1.setFont(new java.awt.Font("Dialog", 1, 16)); // NOI18N
        jLabel1.setText("FORMULARIO DE REGISTRO");

        jLabelNamePlace.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNamePlace.setText("NOMBRE DEL LUGAR:");

        jLabelVotingCapacity.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelVotingCapacity.setText("CAPACIDAD DE VOTANTES POR MESA:");

        jLabelAddressPlace1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelAddressPlace1.setText("DIRECCIÓN DEL LUGAR:");

        jSliderNumTables.setMajorTickSpacing(1);
        jSliderNumTables.setMaximum(15);
        jSliderNumTables.setMinimum(1);
        jSliderNumTables.setPaintLabels(true);
        jSliderNumTables.setPaintTicks(true);
        jSliderNumTables.setValue(8);
        jSliderNumTables.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderNumTablesStateChanged(evt);
            }
        });

        jLabelNumTables1.setFont(new java.awt.Font("Dialog", 1, 14)); // NOI18N
        jLabelNumTables1.setText("NÚMERO DE MESAS:");

        jSliderVoterCapacity.setMajorTickSpacing(10);
        jSliderVoterCapacity.setMaximum(200);
        jSliderVoterCapacity.setMinimum(50);
        jSliderVoterCapacity.setPaintLabels(true);
        jSliderVoterCapacity.setPaintTicks(true);
        jSliderVoterCapacity.setValue(125);
        jSliderVoterCapacity.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jSliderVoterCapacityStateChanged(evt);
            }
        });

        jButtonRegisterVotingPlace.setBackground(new java.awt.Color(0, 176, 172));
        jButtonRegisterVotingPlace.setText("REGISTRAR");
        jButtonRegisterVotingPlace.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonRegisterVotingPlaceActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelTituloGestionLugarVotacion, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(jLabelNamePlace)
                                .addComponent(jtxtNamePlace)
                                .addComponent(jtxtAddressPlace, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE))
                            .addComponent(jLabelAddressPlace1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNumTables1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelContNumTables))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelVotingCapacity)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabelContVoterCapacity))
                            .addComponent(jSliderVoterCapacity, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jSliderNumTables, javax.swing.GroupLayout.PREFERRED_SIZE, 450, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButtonRegisterVotingPlace, javax.swing.GroupLayout.PREFERRED_SIZE, 203, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 425, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabelTituloGestionLugarVotacion)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabelNamePlace)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtNamePlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabelAddressPlace1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jtxtAddressPlace, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelNumTables1)
                    .addComponent(jLabelContNumTables))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderNumTables, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelVotingCapacity)
                    .addComponent(jLabelContVoterCapacity))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSliderVoterCapacity, javax.swing.GroupLayout.DEFAULT_SIZE, 52, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jButtonRegisterVotingPlace)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    /**
     * Acción del boton que registra un lugar de votación.  
     * @param evt 
     */
    private void jButtonRegisterVotingPlaceActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonRegisterVotingPlaceActionPerformed
        //recuperemos los valores 
        String namePlace = this.jtxtNamePlace.getText();
        String addressPlace = this.jtxtAddressPlace.getText();
        int numTables = this.jSliderNumTables.getValue();
        int voterCapacity = this.jSliderVoterCapacity.getValue();
        try {
            VotingPlace objPlace = new VotingPlace(namePlace, addressPlace, numTables);
           
            ServiceVotingPlace objServiceVoting = new ServiceVotingPlace();
            //creamos el lugar de votacion 
            int result = objServiceVoting.addVotingPlace(objPlace);
            if (result == 1) {
                //creo las mesas 
                for (int i = 1; i <= numTables; i++) {
                    objPlace.addVotingTable(namePlace+"_"+i, voterCapacity);
                }
                for (int i = 0; i < objPlace.getNumTables(); i++) {
                    result = objServiceVoting.addVotingTable(objPlace.getLstTables().get(i));
                }
                
                
                JOptionPane.showInternalMessageDialog(this, "Lugar de votación insertado con éxito","Insertar lugar de votación", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showInternalMessageDialog(this, "Eror en la inserción","Insertar lugar de votación", JOptionPane.ERROR_MESSAGE);
            }
          
        } catch (Exception e) {
            System.out.println("Error inesperado");
        }
        
    }//GEN-LAST:event_jButtonRegisterVotingPlaceActionPerformed
    /**
     * Evento se dispara cuando cmabia el valor del slider de NumTables 
     * @param evt 
     */
    private void jSliderNumTablesStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderNumTablesStateChanged
        // TODO add your handling code here:
        this.jLabelContNumTables.setText(String.valueOf(this.jSliderNumTables.getValue()));
    }//GEN-LAST:event_jSliderNumTablesStateChanged
    /**
     * Evento se dispara cuando cambia el valor del slider de VoterCapacity
     * @param evt 
     */
    private void jSliderVoterCapacityStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jSliderVoterCapacityStateChanged
        // TODO add your handling code here:
        this.jLabelContVoterCapacity.setText(String.valueOf(this.jSliderVoterCapacity.getValue()));
    }//GEN-LAST:event_jSliderVoterCapacityStateChanged


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonRegisterVotingPlace;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabelAddressPlace1;
    private javax.swing.JLabel jLabelContNumTables;
    private javax.swing.JLabel jLabelContVoterCapacity;
    private javax.swing.JLabel jLabelNamePlace;
    private javax.swing.JLabel jLabelNumTables1;
    private javax.swing.JLabel jLabelTituloGestionLugarVotacion;
    private javax.swing.JLabel jLabelVotingCapacity;
    private javax.swing.JSlider jSliderNumTables;
    private javax.swing.JSlider jSliderVoterCapacity;
    private javax.swing.JTextField jtxtAddressPlace;
    private javax.swing.JTextField jtxtNamePlace;
    // End of variables declaration//GEN-END:variables
}
